In [1]:
# Importing the required library
import numpy as np

In [2]:
# Creating single dimensional array
singleDimArray = np.array([1,2,3,4,5])
print(singleDimArray)

[1 2 3 4 5]


In [3]:
# We have created single dimensional array, lets check what is the type of singleDimArray
print(type(singleDimArray))

<class 'numpy.ndarray'>


In [4]:
# Creating two dimensional array
twoDimArray = np.array([(1,2,3),(4,5,6)], dtype=int)
print(twoDimArray)

[[1 2 3]
 [4 5 6]]


In [5]:
# We have created two dimensional array, lets try to access their value by row and index position
print(twoDimArray[0]) # By Row Position - array[rowIndex]
print(twoDimArray[1][1]) # By Row and Column Position - array[rowIndex][columnIndex]

[1 2 3]
5


In [6]:
print(singleDimArray.shape)
print(twoDimArray.shape) # prints the dimension of the array

(5,)
(2, 3)


In [7]:
threeDimArray = np.array([[(1,2,3),(4,5,6)],[(7,8,9),(1,2,3)]])

In [8]:
print(threeDimArray) # Matrix within Matrix

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [9]:
threeDimArray[0] # First Matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
threeDimArray[1] # Second Matrix

array([[7, 8, 9],
       [1, 2, 3]])

In [11]:
threeDimArray[0][0] # First Matrix, First Row

array([1, 2, 3])

In [12]:
threeDimArray[1][0][0] # Second Matrix, First Row and First Value

7

In [13]:
# Filling value in np array
# At time we may need to fill define
# Empty array - random value
# With filled with zero
# With filled with ones
# With constant fill 
# Identity Matrix

In [14]:
# np.empty creates an array from available memory space,
# leaving whatever values happened to be hanging around in memory as the values. 
# These values may or may not be zeros.
emptyArray = np.empty((3,3))
print(emptyArray)

[[0.00000000e+000 6.90844225e-310 6.90844558e-310]
 [5.39489646e-317 5.39489646e-317 6.90844564e-310]
 [6.90841600e-310 0.00000000e+000 3.95252517e-322]]


In [15]:
zeroArray = np.zeros((3,3)) # By Default the np array fills zero with float type
print(zeroArray)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
np.zeros((3,3),dtype=int) # We can change the type of array to be filled in the array by specifying dtype

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
np.ones((3,3),dtype=int) # Filling matrix with one

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
np.full((3,3),5) # Filling matrix with constant value

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [19]:
np.arange(10,25,5) # similar to for loop increment np.arrange(starting value, ending value, increment)

array([10, 15, 20])

In [20]:
np.arange(1,10,1) # Displaying value from 1 to 10 by incrementing by 1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(1,10,0.5) # We can also increment by decimal point

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [22]:
value = np.linspace(0,2,20) # creates a equal spaced elements within the range 

In [23]:
for each in value:
    print(each)

0.0
0.10526315789473684
0.21052631578947367
0.3157894736842105
0.42105263157894735
0.5263157894736842
0.631578947368421
0.7368421052631579
0.8421052631578947
0.9473684210526315
1.0526315789473684
1.1578947368421053
1.263157894736842
1.3684210526315788
1.4736842105263157
1.5789473684210527
1.6842105263157894
1.789473684210526
1.894736842105263
2.0


In [24]:
value = np.linspace(1,100,10)
for each in value:
    print(each)

1.0
12.0
23.0
34.0
45.0
56.0
67.0
78.0
89.0
100.0


In [25]:
np.eye(4) # creates indetity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])